language: node_js
node_js:
  - "14"
  - "16"
matrix:
  fast_finish: true
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
dist: trusty
sudo: required
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=54312
before_script:
  - psql --cluster 11/main -c 'create user codenautas_user password $$test_pass$$;' -U postgres
  - psql --cluster 11/main -c 'create database test_db owner codenautas_user;' -U postgres
  - psql -c 'create user codenautas_user password $$test_pass$$;' -U postgres
  - psql -c 'create database test_db owner codenautas_user;' -U postgres
  - cp travis-test-config.yaml local-config.yaml