language: node_js
node_js:
  - "14"
  - "16"
matrix:
  fast_finish: true
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
dist: trusty
sudo: required
addons:
  postgresql: "12"
before_script:
  - psql -c 'create user codenautas_user password $$test_pass$$;' -U postgres
  - psql -c 'create database test_db owner codenautas_user;' -U postgres
  - cp travis-test-config.yaml local-config.yaml